### ISSUE TITLE
Update CONTRIBUTING doc

### ISSUE THREAD

**Issue by coltonehrman** [Software-Developer-Academy/mentor-match#101]
Update CONTRIBUTING doc with must have information on self-assigning issues, and updating progress and linking PR to issue to close it out once PR is merged.

**Comment by Ragudos** [comment]
Can this be a video or a long explanation on the markdown?

**Comment by coltonehrman** [comment]
> Can this be a video or a long explanation on the markdown?

I think we still need some text info, but an additional video would be awesome!

**Comment by Ragudos** [comment]
Hmm. Alright.
