### ISSUE TITLE
Update User DB model for Account Questionnaire form

### ISSUE THREAD

**Issue by coltonehrman** [Software-Developer-Academy/mentor-match#125]
Update the User DB model to include data related to account questionnaire form.

**Comment by Ramzi-Abidi** [comment]
May I take this issue @coltonehrman @tjay22 ?

**Comment by tjay22** [comment]
@Ramzi-Abidi Sure!

**Comment by Ramzi-Abidi** [comment]
Hello team,

I found out that User model already has "skills" property.

![image](https://github.com/Software-Developer-Academy/mentor-match/assets/69228547/bcc3b647-9029-4561-95dc-baddf76cc8ea)

So, I'm wondering what else we could add to it for the questionnaire form. 

I thought this how the **questionnaire** will look like:

![image](https://github.com/Software-Developer-Academy/mentor-match/assets/69228547/e73fb5bc-ac4a-483b-9324-51bf095c173b)

**Comment by tjay22** [comment]
@Ramzi-Abidi Maybe you can use this [JSON file](https://github.com/Software-Developer-Academy/mentor-match/blob/feature/reusable-signup-questions/src/data/signup-questions.tsx) as a reference for the DB model. Currently on the frontend, the onSubmit function is logging out a JSON string with the IDs and values.

The signup questionnaire is a multi question form so maybe it's better to create a single field that saves all that data? Other things to note:
- the questionnaire is optional and the mentee can choose to skip it
- the above-mentioned JSON file was only created to simulate real data. The goal is to get the dynamic data, like the subjects, from the database. The static data can come from a JSON file.
- the list of subjects will change based on the mentors available to teach said subjects. The same goes for the languages field.

If you would like to test out the form, use [this branch](https://github.com/Software-Developer-Academy/mentor-match/tree/feature/reusable-signup-questions). 

Thanks for contributing!
