### ISSUE TITLE
Input validations on /signup form

### ISSUE THREAD

**Issue by coltonehrman** [Software-Developer-Academy/mentor-match#23]
### Summary

Add some input validation logic on client for `/signup` form.

### Why?

Validations on client-side improve user experience and "save" unnecessary network calls from the client with invalid inputs. Relying on browser's to handle client-side validations leaves out unsupported browser and also leaves a gap for some sort of validations such as password/passwordConfirm matching.

### Validations

- Name should be between A-B amount of characters long and should only include alphabetical characters, hyphens, and apostrophes.
- Email should match a verified email format
- Password should follow strict format/recommendations to create secure password
- Password & password confirmation should match

**Comment by harunugurlu** [comment]
Hi, @coltonehrman working on it!

**Comment by coltonehrman** [comment]
> Hi, @coltonehrman working on it!

Thank you @harunugurlu. Please remember to assign the issue to yourself and also move it to in progress on the project board :)

**Comment by harunugurlu** [comment]
> > Hi, @coltonehrman working on it!
> 
> Thank you @harunugurlu. Please remember to assign the issue to yourself and also move it to in progress on the project board :)

Sorry about this :(, I am new to GitHub Issues

**Comment by coltonehrman** [comment]
> > > Hi, @coltonehrman working on it!
> 
> > 
> 
> > Thank you @harunugurlu. Please remember to assign the issue to yourself and also move it to in progress on the project board :)
> 
> 
> 
> Sorry about this :(, I am new to GitHub Issues 

No worries :)

**Comment by coltonehrman** [comment]
Closed by #25
