### ISSUE TITLE
Add mobile responsive design to /signup page

### ISSUE THREAD

**Issue by coltonehrman** [Software-Developer-Academy/mentor-match#27]
Check the /signup page and add any mobile responsive styling to it to ensure it look great on all device screens/sizes.

**Comment by willy264** [comment]
okay,  so it is the /signup figma ui I will be using

**Comment by coltonehrman** [comment]
@willy264 Did you want to take this issue, or just work on a wireframe?

**Comment by willy264** [comment]
@coltonehrman Yeah, I want this issue.

**Comment by willy264** [comment]
@coltonehrman Can I use tailwind or another framework?

**Comment by coltonehrman** [comment]
> @coltonehrman Can I use tailwind or another framework?

Our project is setup to use tailwind, so please try to stick with that. If you want to bring in something else let's discuss it first before you spend much time on that.

**Comment by willy264** [comment]
got it
