### ISSUE TITLE
Add session management in App

### ISSUE THREAD

**Issue by coltonehrman** [Software-Developer-Academy/mentor-match#49]
We need to integrate some sort of session management to the App, to maintain session state when a user logs in to the App.

We can kick-off discuss and brainstorming in terms of how we want to do this and what libs/tools we could utilize.

**Comment by coltonehrman** [comment]
To kickoff initial discussion point - https://nextjs.org/docs/app/building-your-application/authentication#session-management

**Comment by Ragudos** [comment]
Will it be possible to roll our own with an encrypting library, a database, and use OAuth2 to not worry about CSRF and such?

**Comment by coltonehrman** [comment]
> Will it be possible to roll our own with an encrypting library, a database, and use OAuth2 to not worry about CSRF and such?

Absolutely! The world is our oyster here so we can do whatever we want :) If you find that interesting I would love to have you work on that and incorporate it into the project.

**Comment by Ragudos** [comment]
Awesome! I checked around and it seems the project is still in its infancy which I like. I will set it up later or by tomorrow and try to work on something. May I know what the goal of this web project is?

For the linked pull request, it looks great. I'll probably add something onto it (probably user role?) when it gets merged.

**Comment by coltonehrman** [comment]
> Awesome! I checked around and it seems the project is still in its infancy which I like. I will set it up later or by tomorrow and try to work on something. May I know what the goal of this web project is?
> 
> For the linked pull request, it looks great. I'll probably add something onto it (probably user role?) when it gets merged.

Awesome! Looking forward to it!

Check out https://github.com/Software-Developer-Academy/mentor-match/discussions/4 for some of our "goal" discussions.

Yeah, feel free to suggest changes or add-on later.
