### ISSUE TITLE
Add Session DB to store generated sessions

### ISSUE THREAD

**Issue by coltonehrman** [Software-Developer-Academy/mentor-match#62]
Include Session model/schema for storing newly generated sessions across app.

Use case: query Sessions to find "active" users that are online

**Comment by Ragudos** [comment]
Hmm, will we base this on a `loggedInAt` date AND `lastActivityDate` and have some kind of a 5 minute offset for `lastActivityDate` before saying that a user is offline?

**Comment by coltonehrman** [comment]
> Hmm, will we base this on a `loggedInAt` date AND `lastActivityDate` and have some kind of a 5 minute offset for `lastActivityDate` before saying that a user is offline?

Yeah good question. I hadn't thought that far into it lol

We could do a standard `createdAt` and `updatedAt` and use those to determine activity.

**Comment by Ragudos** [comment]
I see. I can add this and also the logic for it when logging in or signing up.
