### ISSUE TITLE
3rd party Auth provider integration (ie: Google, FB, Github, etc.)

### ISSUE THREAD

**Issue by coltonehrman** [Software-Developer-Academy/mentor-match#65]
Look into integrating 3rd party authentication providers to enable other auth strategies.

**Comment by ogeeDeveloper** [comment]
Which authentication third party library should be used for the oauth?

**Comment by tjay22** [comment]
> Which authentication third party library should be used for the oauth?

@ogeeDeveloper I guess we can start with Google and then decide if we want to include other providers? What do you think?

**Comment by ogeeDeveloper** [comment]
I mean if Firebase, supabase or next auth with be the library that provides the 3rd party authentication?

**Comment by tjay22** [comment]
> I mean if Firebase, supabase or next auth with be the library that provides the 3rd party authentication?

@ogeeDeveloper I remember clerk and next auth being mentioned during the initial discussions. I don't have experience with either one as I've only worked with Firebase before. Which library so you have experience with?
