### ISSUE TITLE
Create a Feedback form

### ISSUE THREAD

**Issue by coltonehrman** [Software-Developer-Academy/mentor-match#66]
Create simple feedback form that can be submitted anonymously (if wanted).
The form should collect a textarea input with a max character limit.

Can create the form as an independent component for now and determine the different places we want to integrate it in.

**Comment by CoDedArch** [comment]
I have started to work on feedback form component

**Comment by coltonehrman** [comment]
@CoDedArch Any updates on this one?

**Comment by CoDedArch** [comment]
Yes, so i have picked up from where I left off today.
