### ISSUE TITLE
Create "Swiping" UI

### ISSUE THREAD

**Issue by coltonehrman** [Software-Developer-Academy/mentor-match#69]
Create a Tinder like swiping page which will display a simple stack of cards and allow the user to swipe left or right on them.

*Logic & backend functions will be done separately, this is just the UI portion*

**Comment by Ragudos** [comment]
A reusable component?

**Comment by Ragudos** [comment]
I watched something that looked good, I might try it

**Comment by coltonehrman** [comment]
Here is the wireframe I put together for this.
![Screenshot 2024-04-23 082418](https://github.com/Software-Developer-Academy/mentor-match/assets/12456288/76643686-767d-427f-b8b4-72f13d463c08)

**Comment by Ragudos** [comment]
Nice! Yeah, the thing I watched look almost like this one! Maybe we can use icons instead of Yes and no?

**Comment by coltonehrman** [comment]
> Nice! Yeah, the thing I watched look almost like this one! Maybe we can use icons instead of Yes and no?
> 
> 

Yeah, that's just a wireframe. We can change to use icons or whatever there.
